/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: examples/themes/custom/astryx-v0.theme.ts
 * Command: astryx theme build examples/themes/custom/astryx-v0.theme.ts --out examples/themes/custom/built/astryx-v0.css
 * CLI: @astryxdesign/cli@0.6.3
 * Core: @astryxdesign/core@0.6.3
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
