/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: examples/themes/custom/astryx-v0.theme.ts
 * Command: astryx theme build examples/themes/custom/astryx-v0.theme.ts --out examples/themes/custom/built/astryx-v0.css
 * CLI: @astryxdesign/cli@0.6.3
 * Core: @astryxdesign/core@0.6.3
 */

/// <reference path="./astryx-v0.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const astryxV0Theme: DefinedTheme;
